/*
 * generated by Xtext
 */
package com.first8.elasticsearch.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.first8.elasticsearch.dsl.ui.internal.SearchDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SearchDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SearchDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SearchDslActivator.getInstance().getInjector(SearchDslActivator.COM_FIRST8_ELASTICSEARCH_DSL_SEARCHDSL);
	}
	
}
