/*
* generated by Xtext
*/
package com.first8.elasticsearch.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SearchDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.first8.elasticsearch.dsl.ui.internal.SearchDslActivator.getInstance().getInjector("com.first8.elasticsearch.dsl.SearchDsl");
	}
	
}
