/*
* generated by Xtext
*/
package com.first8.elasticsearch.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SearchDslStandaloneSetup extends SearchDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SearchDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

