/*
 * generated by Xtext
 */
package com.first8.elasticsearch.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SearchDslRuntimeModule extends com.first8.elasticsearch.dsl.AbstractSearchDslRuntimeModule {

}
