/*
 * generated by Xtext
 */
package com.first8.elasticsearch.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SearchDslUiModule extends com.first8.elasticsearch.dsl.ui.AbstractSearchDslUiModule {
	public SearchDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
