/**
 * generated by Xtext
 */
package com.first8.elasticsearch.dsl.validation;

import com.first8.elasticsearch.dsl.validation.AbstractSearchDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SearchDslValidator extends AbstractSearchDslValidator {
}
