/*
 * generated by Xtext
 */
package com.first8.elasticsearch.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSearchDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.first8.elasticsearch.dsl.search.SearchPackage.eINSTANCE);
		return result;
	}
}
