/*
* generated by Xtext
*/
package com.first8.elasticsearch.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.first8.elasticsearch.dsl.services.SearchDslGrammarAccess;

public class SearchDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SearchDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.first8.elasticsearch.dsl.parser.antlr.internal.InternalSearchDslParser createParser(XtextTokenStream stream) {
		return new com.first8.elasticsearch.dsl.parser.antlr.internal.InternalSearchDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SearchDSL";
	}
	
	public SearchDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SearchDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
