/*
* generated by Xtext
*/
package com.first8.elasticsearch.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SearchDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/first8/elasticsearch/dsl/parser/antlr/internal/InternalSearchDsl.tokens");
	}
}
