/*
 * generated by Xtext
 */
package com.first8.elasticsearch.dsl.ui.contentassist

import com.first8.elasticsearch.dsl.ui.contentassist.AbstractSearchDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SearchDslProposalProvider extends AbstractSearchDslProposalProvider {
}
